name: Sync Secrets from Vault

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    env:
      VAULT_VERSION: "1.15.0"
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_REPO: ${{ github.repository }}
      SECRET_PATH: "kvV2/Vault-POC/backend/dev"

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get secrets from Vault
      - name: Get secrets from Vault
        id: vault-secrets
        uses: hashicorp/vault-action@v2.4.1
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          path: ${{ env.SECRET_PATH }}
          method: token
          exportEnv: true  # Exports secrets as environment variables

      # Step 3: Print retrieved secret keys (SAFE LOGGING)
      - name: Print retrieved secret keys
        run: |
          echo "Secrets successfully retrieved from Vault!"
          echo "Available secret keys:"
          env | grep 'VAULT_' | cut -d= -f1  # Prints only the keys

      # Step 4: Create a .env file
      - name: Create .env file
        run: |
          echo "Saving secrets to .env file..."
          env | grep 'VAULT_' | sed 's/^VAULT_//' > .env
          echo ".env file created successfully!"

      # Step 5: Confirm successful execution
      - name: Confirm success
        run: echo "Vault secrets have been successfully retrieved and saved."
